# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import kabinet.common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Площади',
                'verbose_name': 'Площадь',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_ad_agency', models.BooleanField(default=False, verbose_name='Рекламное агенство')),
                ('is_agency', models.BooleanField(default=False, verbose_name='Агенство недвижимости')),
                ('users', kabinet.common.fields.OptionalManyToManyField(blank=True, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name_plural': 'Компании',
                'verbose_name': 'Компания',
            },
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('subdomain', kabinet.common.fields.MaxOptionalCharField(blank=True, max_length=255, null=True, verbose_name='Поддомен')),
            ],
            options={
                'verbose_name_plural': 'Комплексы',
                'verbose_name': 'Комплекс',
            },
        ),
        migrations.CreateModel(
            name='PurchaseCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Условия покупки',
                'verbose_name': 'Условие покупки',
            },
        ),
        migrations.CreateModel(
            name='RealtyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Типы недвижимости',
                'verbose_name': 'Тип недвижимости',
            },
        ),
        migrations.CreateModel(
            name='RoomsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Комнатности',
                'verbose_name': 'Комнатность',
            },
        ),
    ]
