# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kabinet.common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Площадь',
                'verbose_name_plural': 'Площади',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_ad_agency', models.BooleanField(default=False, verbose_name='Рекламное агенство')),
                ('is_agency', models.BooleanField(default=False, verbose_name='Агенство недвижимости')),
                ('users', kabinet.common.fields.OptionalManyToManyField(blank=True, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('subdomain', kabinet.common.fields.MaxOptionalCharField(blank=True, max_length=255, null=True, verbose_name='Поддомен')),
                ('metrika_source_id', kabinet.common.fields.OptionalBigIntegerField(blank=True, null=True, verbose_name='Счетчик Я.Метрики')),
            ],
            options={
                'verbose_name': 'Комплекс',
                'verbose_name_plural': 'Комплексы',
            },
        ),
        migrations.CreateModel(
            name='PurchaseCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Условие покупки',
                'verbose_name_plural': 'Условия покупки',
            },
        ),
        migrations.CreateModel(
            name='RealtyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип недвижимости',
                'verbose_name_plural': 'Типы недвижимости',
            },
        ),
        migrations.CreateModel(
            name='RoomsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Комнатность',
                'verbose_name_plural': 'Комнатности',
            },
        ),
        migrations.CreateModel(
            name='YaDirectCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(verbose_name='Номер')),
                ('type', models.CharField(choices=[('search', 'Поисковая'), ('rsya', 'РСЯ')], max_length=255, verbose_name='Тип')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ya_direct_campaigns', to='realty.Complex', verbose_name='Комплекс')),
            ],
            options={
                'verbose_name': 'Номер кампании в Я.Директе',
                'verbose_name_plural': 'Номера кампаний в Я.Директе',
            },
        ),
    ]
