# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_builder',
            field=models.BooleanField(default=False, verbose_name='Застройщик'),
        ),
    ]
