# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import kabinet.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Доп. источники',
                'verbose_name': 'Доп. источник',
            },
        ),
        migrations.CreateModel(
            name='MainSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Основные источники',
                'verbose_name': 'Основной источник',
            },
        ),
        migrations.AddField(
            model_name='phonecall',
            name='additional_source',
            field=kabinet.common.fields.OptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calls.AdditionalSource', verbose_name='Доп. источник'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='main_source',
            field=kabinet.common.fields.OptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calls.MainSource', verbose_name='Основной источник'),
        ),
    ]
