# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import kabinet.common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('realty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecall',
            name='ad_agency',
            field=kabinet.common.fields.OptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_agency_calls', related_query_name='ad_agency_calls', to='realty.Company', verbose_name='Рекламное агенство'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='answer_tags',
            field=kabinet.common.fields.OptionalManyToManyField(blank=True, related_name='calls', related_query_name='call', to='calls.AnswerTag', verbose_name='Ответы на вопросы'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='areas',
            field=kabinet.common.fields.OptionalManyToManyField(blank=True, related_name='calls', related_query_name='call', to='realty.Area', verbose_name='Площадь'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='assigned_to',
            field=kabinet.common.fields.OptionalManyToManyField(blank=True, related_name='assigned_calls', related_query_name='assigned_call', to=settings.AUTH_USER_MODEL, verbose_name='Кому был распределен звонок'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='caller_actions',
            field=kabinet.common.fields.OptionalManyToManyField(blank=True, related_name='calls', related_query_name='call', to='calls.CallerAction', verbose_name='Действия звонящего'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='company',
            field=kabinet.common.fields.OptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', related_query_name='call', to='realty.Company', verbose_name='Застройщик'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='complex',
            field=kabinet.common.fields.OptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', related_query_name='calls', to='realty.Complex', verbose_name='Комплекс'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='complex_redirected_to',
            field=kabinet.common.fields.OptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirected_calls', related_query_name='redirected_call', to='realty.Complex', verbose_name='Комплекс в отчет'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='listened_by',
            field=kabinet.common.fields.OptionalManyToManyField(blank=True, related_name='listened_calls', related_query_name='listened_call', to=settings.AUTH_USER_MODEL, verbose_name='Кто прослушал'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='markers',
            field=kabinet.common.fields.OptionalManyToManyField(blank=True, related_name='calls', related_query_name='call', to='calls.Marker', verbose_name='Доп. маркеры'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='purchase_conditions',
            field=kabinet.common.fields.OptionalManyToManyField(blank=True, related_name='calls', related_query_name='call', to='realty.PurchaseCondition', verbose_name='Условия покупки'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='realty_agency_redirected_to',
            field=kabinet.common.fields.OptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirected_to_agency_calls', related_query_name='redirected_to_agency_call', to='realty.Company', verbose_name='Перенаправление звонка в агенство недвижимости'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='realty_type',
            field=kabinet.common.fields.OptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', related_query_name='call', to='realty.RealtyType', verbose_name='Тип недвижимости'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='rooms_counts',
            field=kabinet.common.fields.OptionalManyToManyField(blank=True, related_name='calls', related_query_name='call', to='realty.RoomsCount', verbose_name='Комнатность'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='speech_tags',
            field=kabinet.common.fields.OptionalManyToManyField(blank=True, related_name='calls', related_query_name='call', to='calls.SpeechTag', verbose_name='Речь'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='status',
            field=kabinet.common.fields.OptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calls.PhoneCallStatus', verbose_name='Статус звонка'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='transaction_status',
            field=kabinet.common.fields.OptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', related_query_name='call', to='calls.TransactionStatus', verbose_name='Статус сделки'),
        ),
    ]
