# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 22:50
from __future__ import unicode_literals

from django.db import migrations
import kabinet.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_auto_20180627_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonecall',
            name='is_caller_male',
        ),
        migrations.AddField(
            model_name='phonecall',
            name='sex',
            field=kabinet.common.fields.OptionalCharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True, verbose_name='Пол звонящего'),
        ),
    ]
